"""Synthesis & Citations -- writes the report from ACCEPTED claims only.

A claim that failed verification must not reach this agent even as context: if it
does, it can leak back into the prose and undo the entire pipeline.

Citations are assigned mechanically from claim.paper_id, never generated by the model.
A model asked to write its own citation numbers will eventually renumber them, and a
report whose [3] points at the wrong paper fails on exactly the dimension this project
claims to fix.
"""
from __future__ import annotations

import re

from pydantic import BaseModel, Field

from ..llm.base import LLMClient
from ..models import Citation, PaperRef, Report, Theme, VerifiedClaim
from ..prompts import render


class _ThemeDraft(BaseModel):
    title: str
    claim_ids: list[str] = Field(default_factory=list)
    prose: str = Field(description="Paragraph citing claims by their id in [[C-xxx]] form.")


class _SynthesisDraft(BaseModel):
    themes: list[_ThemeDraft]


def _bibtex(papers: list[PaperRef], order: list[str]) -> str:
    entries = []
    for marker, paper_id in enumerate(order, start=1):
        paper = next((p for p in papers if p.id == paper_id), None)
        if paper is None:
            continue
        first = paper.authors[0].name.split()[-1].lower() if paper.authors else "anon"
        key = re.sub(r"[^a-z0-9]", "", f"{first}{paper.year or ''}") or f"ref{marker}"
        authors = " and ".join(a.name for a in paper.authors) or "Unknown"
        fields = [f"  author  = {{{authors}}}", f"  title   = {{{paper.title}}}"]
        if paper.venue:
            fields.append(f"  journal = {{{paper.venue}}}")
        if paper.year:
            fields.append(f"  year    = {{{paper.year}}}")
        if paper.doi:
            fields.append(f"  doi     = {{{paper.doi}}}")
        entries.append("@article{" + key + ",\n" + ",\n".join(fields) + "\n}")
    return "\n\n".join(entries) + ("\n" if entries else "")


async def synthesize(
    question: str,
    accepted: list[VerifiedClaim],
    papers: list[PaperRef],
    llm: LLMClient,
    *,
    model: str,
) -> Report:
    if not accepted:
        return Report(
            markdown=(
                f"## {question}\n\n"
                "No claims survived verification, so this report states nothing. "
                "Every extracted claim either quoted text absent from its source or "
                "was not supported by the quote it cited.\n"
            )
        )

    by_id = {vc.claim.id: vc for vc in accepted}
    listing = "\n".join(
        f"- [[{vc.claim.id}]] {vc.claim.text}" for vc in accepted
    )
    prompt = render("synthesizer", question=question, claims=listing)
    draft, _ = await llm.complete_json(prompt, model=model, schema=_SynthesisDraft)

    # Assign citation markers in order of first appearance. Mechanical, not modelled.
    marker_of: dict[str, int] = {}
    order: list[str] = []
    claims_of_paper: dict[str, list[str]] = {}

    def cite(match: re.Match) -> str:
        claim_id = match.group(1)
        vc = by_id.get(claim_id)
        if vc is None:
            return ""  # model referenced a claim that was not accepted -- drop it
        paper_id = vc.claim.paper_id
        if paper_id not in marker_of:
            marker_of[paper_id] = len(order) + 1
            order.append(paper_id)
        claims_of_paper.setdefault(paper_id, []).append(claim_id)
        return f"[{marker_of[paper_id]}]"

    sections: list[str] = [f"## {question}\n"]
    themes: list[Theme] = []
    for theme in draft.themes:
        prose = re.sub(r"\[\[([^\]]+)\]\]", cite, theme.prose).strip()
        if not prose:
            continue
        sections.append(f"### {theme.title}\n\n{prose}\n")
        kept = [cid for cid in theme.claim_ids if cid in by_id]
        themes.append(Theme(title=theme.title, claim_ids=kept))

    if order:
        refs = "\n".join(
            f"{marker_of[pid]}. {next(p.title for p in papers if p.id == pid)}"
            + (f" ({next(p.year for p in papers if p.id == pid)})"
               if next((p.year for p in papers if p.id == pid), None) else "")
            for pid in order
        )
        sections.append(f"### References\n\n{refs}\n")

    return Report(
        markdown="\n".join(sections),
        citations=[
            Citation(marker=marker_of[pid], paper_id=pid,
                     claim_ids=sorted(set(claims_of_paper.get(pid, []))))
            for pid in order
        ],
        themes=themes,
        bibtex=_bibtex(papers, order),
    )
