"""Synthesis & Citations -- writes the final report from ACCEPTED claims only.

Input is `Run.accepted_claims()` and nothing else. A claim that failed verification
must not reach this agent even as context -- if it does, it can leak back into the
prose and undo the whole pipeline.

Steps: group accepted claims into themes, order themes into a narrative, write the
report with inline [n] markers, then emit the citation map and BibTeX.

Citations are assigned mechanically from claim.paper_id, NOT generated by the model.
A model asked to write its own citation numbers will eventually renumber them.

TODO(Track A): implement.
"""
from __future__ import annotations

from ..llm.base import LLMClient
from ..models import PaperRef, Report, VerifiedClaim


async def synthesize(
    question: str,
    accepted: list[VerifiedClaim],
    papers: list[PaperRef],
    llm: LLMClient,
    *,
    model: str,
) -> Report:
    raise NotImplementedError("TODO(Track A)")
